apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run:  @multi-pod
  name: @multi-pod
spec:
  containers:
  - image: machlovi/tf_threading:v2
    name: "p1"
    imagePullPolicy: IfNotPresent
    #  Using CMD to acces run the python file and change 
    #  the @threading to a value to a value that will be pass while runing bash file
    command: ["/bin/bash", "-c"]
    args: ["python3 /5in1.py --n @threading"]
  restartPolicy: Never